name: azure-cli
version: '2.0.25'
summary: Command-line tools for Azure
description: |
  This is my-snap's description. You have a paragraph or two to tell the
  most important story about your snap. Keep it under 100 words though,
  we live in tweetspace and your description wants to look good in the snap
  store.

confinement: strict

apps:
  azure-cli:
    command: bin/az
    plugs:
      - network

parts:
  azure-cli:
    plugin: azure-cli
    source: https://github.com/Azure/azure-cli.git
    source-depth: 1
    source-tag: azure-cli-$SNAPCRAFT_PROJECT_VERSION
    requirements: requirements.txt
    python-packages:
      - azure-nspkg
      - azure-mgmt-nspkg
    install: |
      sed -i 's|python |python3 |' src/azure-cli/az
      cp src/azure-cli/az $SNAPCRAFT_PART_INSTALL/bin